name    'dereklio-gnupg'
version '0.0.5'
source 'git://github.com/dereklio/puppet-gnupg.git'
author 'Deryck Lio'
license 'ASL 2.0'
summary 'Manage gnupg package and public keys'
description 'Manage gnupg installation and handling public keys'
project_page 'https://github.com/dereklio/puppet-gnupg'
